title: Sam Robinson for UNC Student Body President
logo: /assets/img/logo.png
description: "The Official Campaign Website of Sam Robinson for UNC Student Body President. UNC Student Body President Elections is hosting an Election at the University of North Carolina at Chapel Hill and Sam Robinson is the Candidate for the job."
tagline: "Sam Robinson for the University of North Carolina at Chapel Hill Student Body President Elections"
url: "www.samforunc.com"
twitter: 
  username: SamuelCRobinson
  card: summary
social:
  name: Samuel Robinson
  links:
    - https://www.instagram.com/samrobinsonforunc/
    - https://twitter.com/SamuelCRobinson/
show_downloads: true
google_analytics:
plugins:
  - jekyll-seo-tag
theme: S4SBP-theme
